package gameengine.motion.integrators;

import bricklets.Entity;

public interface Integrator {

    /**
     * Returns velocity based on the supplied values
     *
     * @param entity                    the {@link Entity} the velocity will affect
     * @param displacementToDestination the displacement of the entity from the destination, this is a positive when the
     *                                  entity has not passed the destination, and negative if the destination is passed
     * @param elapsedTime               the amount of time over which the velocity will be applied
     * @return the velocity generated by this {@link Integrator}
     */
    public double getVelocity(Entity entity, double displacementToDestination, double elapsedTime);

    public void reset();
}
